# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aman Dogra
email: amandogra@gmail.com
description: A single place to record all the progress I am trying to make or making in my projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amandogra.github.io" # the base hostname & protocol for your site

# Social sites
twitter_username: amandogra
github_username:  amandogra
linkedin_username:    amandogra
google_plus_username: amandogra
facebook_username:    amandogra

# Build settings
sass:
  compressed: true
markdown: kramdown

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
