# Site settings
title:       Aman Dogra
email:       amandogra@gmail.com
author:      Aman Dogra
description: "A single place to record all the progress I am trying to make or making in my projects"
baseurl:     ""
url:         "http://amandogra.github.io/"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: amandogra
stackoverflow_id:
twitter_username:
google_plus_id: amandogra
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
paginate_path: "/blog/page:num/"
sass:
  compressed: true
gems:
  - jekyll-sitemap
